// 就业指导/面试题/最新机试题/todolist「白龙马笔试题」/react版本/src/views/TodoList.jsx
import React, { useState } from "react";
import ListItem from "../components/ListItem";
import styled from "styled-components";
import storage from '../assets/storage';

/* 组件私有的样式 */
const TodoBoxStyled = styled.div`
    box-sizing: border-box;
    margin: 20px auto;
    padding: 10px;
    width: 400px;
    border: 1px solid #DDD;

    .handle {
        padding-bottom: 10px;
        border-bottom: 1px dashed #DDD;

        .createBtn {
            margin-left: 20px;
            background: #93d5ed;
            border-color: #8bd5f0;
        }
    }
`;

const TodoList = function TodoList() {
    /* 创建状态 */
    let [text, setText] = useState('');
    let [list, setList] = useState(() => {
        let value = storage.get('totoList');
        return value || [];
    });

    /* 新增任务 */
    const submit = () => {
        if (text === '') {
            alert('请您先输入内容!');
            return;
        }
        list.push({
            id: +new Date(),
            text
        });
        setList([...list]);
        setText('');
        storage.set('totoList', list);
    };

    /* 子组件改变父组件数据 */
    const change = ({ id, text, type }) => {
        // 删除
        if (type === 'delete') {
            list = list.filter(item => {
                return +item.id !== +id;
            });
            setList([...list]);
            storage.set('totoList', list);
            return;
        }
        // 修改
        list = list.map(item => {
            if (+item.id === +id) {
                item.text = text;
            }
            return item;
        });
        setList([...list]);
        storage.set('totoList', list);
    };

    return <TodoBoxStyled>
        <div className="handle">
            <input type="text" className="textInp"
                value={text}
                onChange={ev => {
                    setText(ev.target.value.trim())
                }} />
            <button className="createBtn" onClick={submit}>新建任务</button>
        </div>
        {list.map(item => {
            return <ListItem key={item.id} info={item} change={change} />;
        })}
    </TodoBoxStyled>;
};
export default TodoList;

// Vue2进阶/day0701/src/views/TodoList.vue
<template>
  <div class="todo-box">
    <div class="handle">
      <el-input placeholder="请输入任务描述" v-model.trim="text" />
      <el-button type="primary" @click="submit">新建任务</el-button>
    </div>
    <list-item v-for="item in list" :key="item.id" :info="item" @handle="handle" />
  </div>
</template>

<script>
import ListItem from "../components/ListItem.vue"
import _ from '@/assets/utils'

export default {
  components: {
    ListItem
  },
  data() {
    // 组件第一次渲染：先从本地存储中获取已有的任务列表
    let cache = _.storage.get('TODO_CACHE')
    return {
      // 任务列表
      list: cache || [],
      // 任务框中输入的内容
      text: ''
    }
  },
  methods: {
    // 新增任务操作
    submit() {
      // 验证text是否为空
      if (this.text.length === 0) {
        this.$message.warning('任务描述不能为空哦~')
        return
      }
      // 新增任务
      this.list.push({
        id: +new Date(),
        text: this.text
      })
      this.text = ''
    },
    // 修改/删除任务
    handle(type, id, text) {
      // type:操作类型  delete/update
      // id:要删除/修改任务项的编号
      // text:如果是修改操作，text存储的是要修改的信息
      if (type === 'delete') {
        this.list = this.list.filter(item => {
          return +item.id !== +id
        })
        return
      }
      if (type === 'update') {
        this.list = this.list.map(item => {
          if (+item.id === +id) {
            item.text = text
          }
          return item
        })
      }
    }
  },
  // 监听任务列表的变化，把最新的信息存储到本地
  watch: {
    list: {
      deep: true,
      handler() {
        _.storage.set('TODO_CACHE', this.list)
      }
    }
  }
}
</script>

<style lang="less" scoped>
.todo-box {
  box-sizing: border-box;
  margin: 50px auto;
  width: 400px;

  .handle {
    padding-bottom: 20px;
    border-bottom: 1px dashed #ddd;
    display: flex;
    justify-content: space-between;
    align-items: center;

    .el-button {
      margin-left: 20px;
    }
  }
}
</style>
